# Generated by Django 4.1.7 on 2023-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminuser', models.CharField(max_length=300)),
                ('adminpass', models.CharField(max_length=300)),
            ],
        ),
    ]
