# Generated by Django 4.1.7 on 2023-06-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_wishlist_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
