# Generated by Django 4.1.7 on 2023-05-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_phone_number_customer_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
    ]
