# Generated by Django 4.1.7 on 2023-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
