# Generated by Django 4.1.7 on 2023-06-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_brand_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(to='myapp.color'),
        ),
    ]
