# Generated by Django 4.1.7 on 2023-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_products_color_products_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.ManyToManyField(to='myapp.gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(to='myapp.size'),
        ),
    ]
