# Generated by Django 4.1.7 on 2023-05-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_productname_product_name_product_image1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='Products',
        ),
    ]
