# Generated by Django 4.2.2 on 2023-06-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('Old', 'Old'), ('New', 'New')], default='New', max_length=50),
        ),
    ]
