# Generated by Django 4.1.7 on 2023-06-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verification_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
