# Generated by Django 4.1.7 on 2023-05-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_image_products_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image1',
            new_name='image',
        ),
    ]
