# Generated by Django 4.1.7 on 2023-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_productoffer_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
