# Generated by Django 4.1.7 on 2023-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_order_cart_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='COD', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='Ordered', max_length=100),
        ),
    ]
