# Generated by Django 4.1.7 on 2023-06-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_order_order_status_alter_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productvariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('color', models.ManyToManyField(to='myapp.color')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='myapp.products')),
                ('size', models.ManyToManyField(to='myapp.size')),
            ],
        ),
    ]
