# Generated by Django 4.1.7 on 2023-06-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_productvariant_description_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='gender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.gender'),
        ),
    ]
