# Generated by Django 4.1.7 on 2023-06-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_productvariant_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
