# Generated by Django 4.1.7 on 2023-06-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
