# Generated by Django 4.1.7 on 2023-06-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_productvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
