# Generated by Django 4.1.7 on 2023-06-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_productvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.productvariant'),
            preserve_default=False,
        ),
    ]
