# Generated by Django 4.1.7 on 2023-06-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_cart_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='gender',
        ),
    ]
