# Generated by Django 4.1.7 on 2023-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('paid_for_order', 'paid_for_order'), ('returned_and_refund', 'returned_and_refund'), ('cancelled_and_refund', 'cancelled_and_refund'), ('withdraw', 'withdraw')], default='deposit', max_length=50),
        ),
    ]
